routes/web.php
<?php

use App\Http\Controllers\AbusadoresController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProvinciaController;
use App\Http\Controllers\MunicipioController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'index'])->name('home');
Route::resources([
    'abusadores' => AbusadoresController::class,
    'provincias' => ProvinciaController::class,
    'municipios' => MunicipioController::class,
    'contactUs' => ContactUsController::class,
]);
//Route::get('/provincia/{provincia}', [ProvinciaController::class, 'show'])->name('provincia.show');

resources/views/layouts/footer.blade.php
<div class="footer_slider">
    <div class="swiper-container" data-autoplay="0" data-loop="1" data-speed="500" data-center="0" data-slides-per-view="responsive" data-xs-slides="4" data-sm-slides="8" data-md-slides="14" data-lg-slides="19" data-add-slides="19">
        <div class="swiper-wrapper">
            <div class="swiper-slide active" data-val="0">

                <a href="gallery.html">				<img class="img-responsive img-full" src="img/f1.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="1">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f2.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="2">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f3.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="3">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f4.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="4">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f5.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="5">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f6.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="6">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f7.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="7">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f8.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="8">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f9.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="9">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f10.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="10">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f11.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="11">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f12.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="12">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f13.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="13">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f14.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="14">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f15.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="15">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f16.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="16">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f17.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="17">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f18.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="18">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f19.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="19">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f1.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="20">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f2.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="21">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f3.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="22">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f4.jpg" alt="">
                </a></div>
            <div class="swiper-slide" data-val="23">
                <a href="gallery.html">

                    <img class="img-responsive img-full" src="img/f5.jpg" alt="">
                </a></div>
        </div>
        <div class="pagination hidden"></div>
    </div>
</div>
<div class="footer-main">
    <div class="container-fluid custom-container">
        <div class="row">
            <div class="col-md-3 col-xl-4">
                <div class="footer-block">
                    <h1 class="footer-title">About Us</h1>
                    <p>En Julio 11, 2021 el pueblo de Cuba sale a las calle a demostrar pacificamente su frustracion de
                        62 años contra el govierno. Nuestra pagina Cataloga los abusos de derechos humanos del regimen
                        comunista en Cuba y identificamos a sus miembros que maltratan a nuestro pueblo.</p>
                    <ul class="soc_buttons">
                        <li><a href=""><i class="fa fa-facebook"></i></a></li>
                        <li><a href="https://twitter.com/julio11cuba"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="https://www.instagram.com/julio11cuba/"><i class="fa fa-instagram"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3 col-xl-2">
                <div class="footer-block">
                    <h1 class="footer-title">Links</h1>
                    <div class="row footer-list-footer">
                        <div class="col-md-6">
                            <ul class="link-list">
                                <li><a href="{{ route('home') }}">Home</a></li>
                                <li><a href="{{ route('abusadores.index') }}">Abusadores</a></li>
                                <li><a href="{{ route('provincias.index') }}">Provincias</a></li>
                                <li><a href="{{ route('municipios.index') }}">Municipios</a></li>
                                <li><a href="{{ route('contactUs.index') }}">Contact Us</a></li>
                            </ul></div>
{{--                        <div class="col-md-6">--}}
{{--                            <ul class="link-list">--}}
{{--                                <li><a href="activity.html">New Works</a></li>--}}
{{--                                <li><a href="author.html">Popular Authors</a></li>--}}
{{--                                <li><a href="author.html">New Authors</a></li>--}}
{{--                                <li><a href="people.html">Career</a></li>--}}
{{--                                <li><a href="faq">FAQ</a></li>--}}
{{--                            </ul>--}}
{{--                        </div>--}}
                    </div>
                </div>
            </div>
            <div class="col-md-3 galerry">
                <div class="footer-block">
                    <h1 class="footer-title">Recent Works</h1>
                    <a href="blog-detail-2.html"><img src="img/g1.jpg" alt=""></a>
                    <a href="blog-detail-2.html"><img src="img/g2.jpg" alt=""></a>
                    <a href="blog-detail-2.html"><img src="img/g3.jpg" alt=""></a>
                    <a href="blog-detail-2.html"><img src="img/g4.jpg" alt=""></a>
                    <a href="blog-detail-2.html"><img src="img/g5.jpg" alt=""></a>
                    <a href="blog-detail-2.html"><img src="img/g6.jpg" alt=""></a>
                    <a href="blog-detail-2.html"><img src="img/g7.jpg" alt=""></a>
                    <a href="blog-detail-2.html"><img src="img/g8.jpg" alt=""></a>
                    <a href="blog-detail-2.html"><img src="img/g9.jpg" alt=""></a>
                    <a href="blog-detail-2.html"><img src="img/g10.jpg" alt=""></a>
                    <a href="blog-detail-2.html"><img src="img/g11.jpg" alt=""></a>
                    <a href="blog-detail-2.html"><img src="img/g12.jpg" alt=""></a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="footer-block">
                    <h1 class="footer-title">Subscribete a nuestras noticias</h1>
                    <form action="./" class="subscribe-form">
                        <input type="text" placeholder="Yout Name" required>
                        <div class="submit-block">
                            <i class="fa fa-envelope-o"></i>
                            <input type="submit" value="">
                        </div>
                    </form>
{{--                    <div class="soc-activity">--}}
{{--                        <div class="soc_ico_triangle">--}}
{{--                            <i class="fa fa-twitter"></i>--}}
{{--                        </div>--}}
{{--                        <div class="message-soc">--}}
{{--                            <div class="date">16h ago</div>--}}
{{--                            <a href="blog-detail-2.html" class="account">@faq</a> vestibulum accumsan est <a href="blog-detail-2.html" class="heshtag">blog-detail-2.htmlmalesuada</a> sem auctor, eu aliquet nisi ornare leo sit amet varius egestas.--}}
{{--                        </div>--}}
{{--                    </div>--}}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="footer-bottom">
    <div class="container-fluid custom-container">
        <div class="col-md-12 footer-end clearfix">
            <div class="left">
                <span class="copy">© 2021. All rights reserved. <span class="white"><a href="blog-detail-2.html"> Julio 11</a></span></span>
                <span class="created">Created by <span class="white"><a href="blog-detail-2.html"> FREEDOM Coders</a></span></span>
            </div>
            <div class="right">
                <a class="btn color-7 size-2 hover-9">About Us</a>
                <a class="btn color-7 size-2 hover-9">Help</a>
                <a class="btn color-7 size-2 hover-9">Privacy Policy</a>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/head.blade.php
<div class="head-bg">
    <div class="head-bg-img"></div>
    <div class="head-bg-content">
        <h1>Denuncia A Comunistas Perseguidors Del Pueblo</h1>
        <p>Sube imagines y videos de abuzos en cuba y identifica a los abuzadores para que nunca los olvidemos!</p>
        <a class="btn color-1 size-1 hover-1 hidden" ><i class="fa fa-facebook"></i>sign up via facebook</a>
        <a class="be-register btn color-3 hidden size-1 hover-6"><i class="fa fa-lock"></i>sign up now</a>
    </div>
</div>

resources/views/layouts/header.blade.php
<div class="container-fluid custom-container">
    <div class="row no_row row-header">
        <div class="brand-be">
            <a href="/">
                <img class="logo-c active be_logo img-responsive" style="max-width: 150px"  src="/img/logo-julio11.png" alt="logo">
            </a>
        </div>
        <div class="header-menu-block">
            <button class="cmn-toggle-switch cmn-toggle-switch__htx"><span></span></button>
            <ul class="header-menu" id="one">
                <li><a href="{{ route('home') }}">Home</a></li>
                <li><a href="{{ route('abusadores.index') }}">Abusadores</a></li>
                <li><a href="{{ route('provincias.index') }}">Provincias</a></li>
                <li><a href="{{ route('municipios.index') }}">Municipios</a></li>
                <li><a href="{{ route('contactUs.index') }}">Contact Us</a></li>
            </ul>
        </div>
        <div class="login-header-block hidden">
            <div class="login_block">
                <a class="btn-login btn color-1 size-2 hover-2" href="" ><i class="fa fa-user"></i>
                    Log in</a>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/leftMenu.blade.php
<div class="col-md-2 left-feild">
    <div class="be-vidget">
        <h3 class="letf-menu-article">
            Provincias
        </h3>
        <div class="creative_filds_block">

            <div class="ul">
                @foreach($provincias as $provincia)
                    <a href="{{route('provincias.show',['provincia'=>$provincia->slug])}}" class="filter">{{$provincia->name}} </a>
                @endforeach
            </div>
        </div>
    </div>
    <div class="be-vidget">
        <h3 class="letf-menu-article">
            Popular Tags
        </h3>
        <div class="tags_block clearfix">
            <ul>
                <li><a data-filter=".category-6" class="filter">photoshop</a></li>
                <li><a data-filter=".category-1" class="filter">graphic</a></li>
                <li><a data-filter=".category-2" class="filter">art</a></li>
                <li><a data-filter=".category-3" class="filter">website</a></li>
                <li><a data-filter=".category-4" class="filter">logo</a></li>
                <li><a data-filter=".category-5" class="filter">identity</a></li>
                <li><a data-filter=".category-6" class="filter">logo design</a></li>
                <li><a data-filter=".category-1" class="filter">interactive</a></li>
                <li><a data-filter=".category-2" class="filter">blue</a></li>
                <li><a data-filter=".category-3" class="filter">branding</a></li>
            </ul>
        </div>
    </div>
</div>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        {{env('APP_NAME','Julio 11')}}
    </title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="img/favicon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ asset('style/bootstrap.min.css') }}">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ asset('style/icon.css') }}">
    <link rel="stylesheet" href="{{ asset('style/loader.css') }}">
    <link rel="stylesheet" href="{{ asset('style/idangerous.swiper.css') }}">
    <link rel="stylesheet" href="{{ asset('style/jquery-ui.css') }}">
    <link rel="stylesheet" href="{{ asset('style/stylesheet.css') }}">

    <!--[if lt IE 10]>
    <link rel="stylesheet" type="text/css" href="{{ asset('style/ie-9.css') }}" />
    <![endif]-->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="be-loader">
    <div class="spinner">
        <p class="circle">
			  <span class="ouro">
			    <span class="left"><span class="anim"></span></span>
			    <span class="right"><span class="anim"></span></span>
			  </span>
        </p>
    </div>
</div>
<!-- THE HEADER -->
<header>
    @include('layouts.header')
</header>

<!-- MAIN CONTENT -->
<div id="content-block">
    @include('layouts.head')

    <div class="container-fluid custom-container">
        <div class="row">
            @include('layouts.leftMenu')
            <div class="col-md-10">
                @yield('content')
            </div>
        </div>
    </div>
</div>
<!-- THE FOOTER -->
<footer>
    @include('layouts.footer')
</footer>

<div class="be-fixed-filter"></div>
<div class="large-popup login">
    <div class="large-popup-fixed"></div>
    <div class="container large-popup-container">
        <div class="row">
            <div class="col-md-8 col-md-push-2 col-lg-6 col-lg-push-3  large-popup-content">
                <div class="row">
                    <div class="col-md-12">
                        <i class="fa fa-times close-button"></i>
                        <h5 class="large-popup-title">Log in</h5>
                    </div>
                    <form action="./" class="popup-input-search">
                        <div class="col-md-6">
                            <input class="input-signtype" type="email" required="" placeholder="Your email">
                        </div>
                        <div class="col-md-6">
                            <input class="input-signtype" type="password" required="" placeholder="Password">
                        </div>
                        <div class="col-xs-6">
                            <div class="be-checkbox">
                                <label class="check-box">
                                    <input class="checkbox-input" type="checkbox" value=""> <span class="check-box-sign"></span>
                                </label>
                                <span class="large-popup-text">
									Stay signed in
								</span>
                            </div>

                            <a href="blog-detail-2.html" class="link-large-popup">Forgot password?</a>
                        </div>
                        <div class="col-xs-6 for-signin">
                            <input type="submit" class="be-popup-sign-button" value="SIGN IN">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="large-popup register">
    <div class="large-popup-fixed"></div>
    <div class="container large-popup-container">
        <div class="row">
            <div class="col-md-10 col-md-push-1 col-lg-8 col-lg-push-2 large-popup-content">
                <div class="row">
                    <div class="col-md-12">
                        <i class="fa fa-times close-button"></i>
                        <h5 class="large-popup-title">Register</h5>
                    </div>
                    <form action="./" class="popup-input-search">
                        <div class="col-md-6">
                            <input class="input-signtype" type="text" required="" placeholder="First Name">
                        </div>
                        <div class="col-md-6">
                            <input class="input-signtype" type="text" required="" placeholder="Last Name">
                        </div>
                        <div class="col-md-6">
                            <div class="be-custom-select-block">
                                <select class="be-custom-select">
                                    <option value="" disabled selected>
                                        Country
                                    </option>
                                    <option value="">USA</option>
                                    <option value="">Canada</option>
                                    <option value="">England</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <input class="input-signtype" type="text" required="" placeholder="Email">
                        </div>
                        <div class="col-md-6">
                            <input class="input-signtype" type="text" required="" placeholder="Password">
                        </div>
                        <div class="col-md-6">
                            <input class="input-signtype" type="text" required="" placeholder="Repeat Password">
                        </div>
                        <div class="col-md-12 be-date-block">
							<span class="large-popup-text">
								Date of birth
							</span>
                            <div class="be-custom-select-block mounth">
                                <select class="be-custom-select">
                                    <option value="" disabled selected>
                                        Mounth
                                    </option>
                                    <option value="">January</option>
                                    <option value="">February</option>
                                    <option value="">March</option>
                                    <option value="">April</option>
                                    <option value="">May</option>
                                    <option value="">June</option>
                                    <option value="">July</option>
                                    <option value="">August</option>
                                    <option value="">September</option>
                                    <option value="">October</option>
                                    <option value="">November</option>
                                    <option value="">December</option>
                                </select>
                            </div>
                            <div class="be-custom-select-block">
                                <select class="be-custom-select">
                                    <option value="" disabled selected>
                                        Day
                                    </option>
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                    <option value="">5</option>
                                    <option value="">6</option>
                                    <option value="">7</option>
                                    <option value="">8</option>
                                    <option value="">9</option>
                                    <option value="">10</option>
                                    <option value="">11</option>
                                    <option value="">12</option>
                                    <option value="">13</option>
                                    <option value="">14</option>
                                    <option value="">15</option>
                                    <option value="">16</option>
                                    <option value="">17</option>
                                    <option value="">18</option>
                                    <option value="">19</option>
                                    <option value="">20</option>
                                    <option value="">21</option>
                                    <option value="">22</option>
                                    <option value="">23</option>
                                    <option value="">24</option>
                                    <option value="">25</option>
                                    <option value="">26</option>
                                    <option value="">27</option>
                                    <option value="">28</option>
                                    <option value="">29</option>
                                    <option value="">30</option>
                                </select>
                            </div>
                            <div class="be-custom-select-block">
                                <select class="be-custom-select">
                                    <option value="" disabled selected>
                                        Year
                                    </option>
                                    <option value="">1996</option>
                                    <option value="">1997</option>
                                    <option value="">1998</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="be-checkbox">
                                <label class="check-box">
                                    <input class="checkbox-input" type="checkbox" required="" value="" > <span class="check-box-sign"></span>
                                </label>
                                <span class="large-popup-text">
									I have read and agree to the <a class="be-popup-terms" href="blog-detail-2.html">Terms of Use</a> and <a class="be-popup-terms" href="blog-detail-2.html">Privacy Policy</a>.
								</span>
                            </div>
                            <div class="be-checkbox">
                                <label class="check-box">
                                    <input class="checkbox-input" type="checkbox" value="" > <span class="check-box-sign"></span>
                                </label>
                                <span class="large-popup-text">
									Send me notifications
								</span>
                            </div>
                        </div>
                        <div class="col-md-6 for-signin">
                            <input type="submit" class="be-popup-sign-button" value="SIGN IN">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- SCRIPTS	 -->
<script src="/script/jquery-2.1.4.min.js"></script>
<script src="/script/jquery-ui.min.js"></script>
<script src="/script/bootstrap.min.js"></script>
<script src="/script/idangerous.swiper.min.js"></script>
<script src="/script/jquery.mixitup.js"></script>
<script src="/script/jquery.viewportchecker.min.js"></script>
<script src="/script/filters.js"></script>
<script src="/script/global.js"></script>
</body>
</html>

resources/views/layouts/topMenu.blade.php
<div class="container-fluid cd-main-content custom-container">
    <div class="row">
        <div class="col-md-2 left-feild">
            <form action="./" class="input-search">
                <input type="text" required="" placeholder="Enter keyword">
                <i class="fa fa-search"></i>
                <input type="submit" value="">
            </form>
        </div>
        <div class="col-md-10 ">
            <div class="for-be-dropdowns">
                <div class="be-drop-down">
                    <i class="icon-projects"></i>
                    <span class="be-dropdown-content"> Projects	</span>
                    <ul class="drop-down-list">
                        <li class="filter" data-filter=".category-1"><a data-type="category-1">Projects</a></li>
                        <li class="filter" data-filter=".category-2"><a data-type="category-2">Work in Progress</a></li>
                        <li class="filter" data-filter=".category-3"><a data-type="category-3">People</a></li>
                    </ul>
                </div>
                <div class="be-drop-down">
                    <i class="icon-creative"></i>
                    <span class="be-dropdown-content">All Creative Filds
							</span>
                    <ul class="drop-down-list">
                        <li class="filter" data-filter=".category-4"><a>Item - 1</a></li>
                        <li class="filter" data-filter=".category-5"><a>Item - 2</a></li>
                        <li class="filter" data-filter=".category-1"><a>Item - 3</a></li>
                    </ul>
                </div>
                <div class="be-drop-down">
                    <i class="icon-features"></i>
                    <span class="be-dropdown-content">Features
							</span>
                    <ul class="drop-down-list">
                        <li class="filter" data-filter=".category-2"><a>Featured</a></li>
                        <li class="filter" data-filter=".category-3"><a>Most Appreciated</a></li>
                        <li class="filter" data-filter=".category-4"><a>Most Viewed</a></li>
                        <li class="filter" data-filter=".category-5"><a>Most Discussed</a></li>
                        <li class="filter" data-filter=".category-1"><a>Most Recent</a></li>
                    </ul>
                </div>
                <div class="be-drop-down">
                    <i class="icon-worldwide"></i>
                    <span class="be-dropdown-content">Worldwide
							</span>
                    <ul class="drop-down-list">
                        <li class="filter" data-filter=".category-2"><a>WorldWide</a></li>
                        <li class="filter" data-filter=".category-3"><a>United States</a></li>
                        <li class="filter" data-filter=".category-4"><a>Germany</a></li>
                        <li class="filter" data-filter=".category-5"><a>United Kingdom</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>